### ISSUE TITLE
CodeSandbox deployment

### ISSUE THREAD

**Issue by SaraVieira** [dojo/dojo-codesandbox-template#10]
Hey! 👋

I am working on the netlify integration for codesandbox and the template needs some changes to be able to work with that :(
We need a build script, is there a way you can add that?

Basically, add all the deps and scripts it would need to work locally and on netlify :/

**Comment by nicknisi** [comment]
Hey! 

Could you give some more information about what you're looking for, and/or maybe an example. The Dojo template is currently a client-side only tempalte in CodeSandbox. Would this make it run the actual build?

**Comment by SaraVieira** [comment]
Yes! That makes sense for running in codesandbox but since we are adding Netfliy integration it needs to build to a directory 

Like what the template would need to run locally

**Comment by nicknisi** [comment]
@SaraVieira Sounds good. Thank you! Will Dojo still be available as a client-side template for normal usage?

**Comment by SaraVieira** [comment]
Yes, sure!

This is merely to allow for all the the deployments and also for download :)

**Comment by nicknisi** [comment]
@SaraVieira Please let me know if you need anything else. Thanks!
